### ISSUE TITLE
Can't build for 5.4.0-59-generic

### ISSUE THREAD

**Issue by dushoff** [Huion-Linux/DIGImend-kernel-drivers-for-Huion#11]
sudo make dkms-install fails with 

`ERROR (dkms apport): binary package for digimend: 10 not found`

Consulting the make log as suggested, I eliminated some warnings by installing stuff, but it did not change the result.

The relevant line in the log seems to be:

`make[6]: *** No rule to make target '/usr/src/linux-headers-5.4.0-59-generic/tools/build/Build.include'.  `

The referenced directory exists (but the file does not, of course).

**Comment by dushoff** [comment]
If I just do `sudo make`, I get:

```
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-59-generic'
make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
```

**Comment by dave2309** [comment]
Try this,
In `Makefile` file line 22-23, replace
`$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) $@`
by 
`$(MAKE) -C $(KDIR) M=$(shell pwd) $@`

Hope that helps

**Comment by dushoff** [comment]
Thanks! The tablet was defective, and I sent it back (I lent it to someone with a Mac). Hope your answer will help someone else.
