### ISSUE TITLE
Works!!

### ISSUE THREAD

**Issue by SimplyCorbett** [Huion-Linux/DIGImend-kernel-drivers-for-Huion#17]
This works with huion kamvas pro 24. Full functionality with xsetwacom. Might want to add it to your device list since I noticed there are no display tablets on the huion section.

**Comment by Rodgers13** [comment]
Do you have functionality of the touch strips? If so, how did you set them?

Thanks in advance.

**Comment by SimplyCorbett** [comment]
Yes.

The touch strip on the kanvas pro 24 has three buttons assigned. Bottom, middle and top.

Key 13 = top
key 15 = bottom

I haven't really tried to figure out how to use key 14. I'm assuming it's just a pause button or something.

**Comment by SimplyCorbett** [comment]
I just viewed your other issue on the digimend-kernel-drivers. You're using the built in tablet GUI for wacom?

This requires xsetwacom to work. This is my setup. Yours may differ. I'm still experimenting with all the buttons so don't have them all assigned yet.

```
#Tablet Monitor Pen stylus              id: 8   type: STYLUS    
#Tablet Monitor Pad pad                 id: 9   type: PAD
xsetwacom set "Tablet Monitor Pad pad" button 1 key Ctrl Z &&
xsetwacom set "Tablet Monitor Pad pad" button 10 key = &&
xsetwacom set "Tablet Monitor Pad pad" button 11 key - &&
xsetwacom set "Tablet Monitor Pad pad" button 13 key + &&
xsetwacom set "Tablet Monitor Pad pad" button 15 key - &&
xsetwacom set "Tablet Monitor Pen stylus" MapToOutput HEAD-0
```

**Comment by Rodgers13** [comment]
Thanks for responding. I'm a noob to Linux. I'm hoping you might be able to help with some confusion with setting xsetwacom. So buttons 13 and 15 can be set to act as a zoom in and out in, for example, in Krita? How did you know 13,14 and 15 corresponded with the touch strip? Have you figured out what numbers in setwacom correspond to the other buttons?

Thanks again, really appreciate it.

**Comment by SimplyCorbett** [comment]
> 
> 
> Thanks for responding. I'm a noob to Linux. I'm hoping you might be able to help with some confusion with setting xsetwacom. So buttons 13 and 15 can be set to act as a zoom in and out in, for example, in Krita? How did you know 13,14 and 15 corresponded with the touch strip? Have you figured out what numbers in setwacom correspond to the other buttons?
> 
> Thanks again, really appreciate it.

When I have the time I'll go over how to find the numbers.

Yes, on my unit 13, 14 and 15 are the left touch strip.

**Comment by SimplyCorbett** [comment]
> stuff

So there are two ways that I know of to find the keys:

1) use xinput test "Tablet Monitor Pad pad"

2) use xev

Press buttons on both to see their number.

Then you just need to map the buttons to your tablet.

**Comment by Rodgers13** [comment]
> 1. use xinput test "Tablet Monitor Pad pad"

Thanks again for the quick response.
After pressing all buttons and touch strips, the output was

motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 
motion a[3]=0 a[4]=0 a[5]=0 

Touch strips didnt give an output at all and buttons stopped giving any output past the 4th button on the right hand side of the tablet.

**Comment by SimplyCorbett** [comment]
Every button on mine gives an output. Two of the buttons share the same key as the touch strip, so that's something I'd have to look into on my end... if I care enough about it.

The left side is a mirror of the right side and vice versa.

If your touchstrip is giving no output at all try replugging in the tablet.

If that fails load up a trial copy of windows 10 and update the huion drivers because it might update the firmware on the device.

If it doesn't work on windows either you need to RMA/return the tablet.

**Comment by Rodgers13** [comment]
Ok, I'll take a look at the firmware. I know that the touch strips and all buttons are functional. I can get full functionality with a java script written for this and similar tablets. It would be nice to figure out what's keeping the digimend drivers from not functioning properly though.

Out of curiosity, what distro are you running?

Thanks again.

**Comment by SimplyCorbett** [comment]
> Out of curiosity, what distro are you running?

It's a bleeding edge distro. I'm not sure if older packages will give you the functionality you need.

**Comment by SimplyCorbett** [comment]
Wanted to just give a quick update. I've experimented with this on another computer and found out that you also need to compile digimend from source here - https://github.com/DIGImend/digimend-kernel-drivers/releases/tag/v10

After compiling and installing the tablet has full functionality.
